name       : python-pathtools
version    : 0.1.2
release    : 3
source     :
    - https://pypi.python.org/packages/source/p/pathtools/pathtools-0.1.2.tar.gz : 7c35c5421a39bb82e58018febd90e3b6e5db34c5443aaaf742b3f33d4655f1c0
license    : MIT
component  : programming.python
summary    : Path utilities for Python
description: |
    Path utilities for Python
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
