name       : python-pathtools
version    : 0.1.2
release    : 7
source     :
    - https://pypi.python.org/packages/source/p/pathtools/pathtools-0.1.2.tar.gz : 7c35c5421a39bb82e58018febd90e3b6e5db34c5443aaaf742b3f33d4655f1c0
homepage   : https://github.com/gorakhargosh/pathtools
license    : MIT
component  : programming.python
summary    : Path utilities for Python
description: |
    Pattern matching and various utilities for file systems paths.
build      : |
    %python3_setup
install    : |
    %python3_install
