name       : python-pathtools
version    : 0.1.0
release    : 1
source     :
    - https://github.com/gorakhargosh/pathtools/archive/v0.1.0.tar.gz : ef1eb29bf4f15059d6ad100e16acc5de36d3f682b3e1b91e6ee8422085c7548b
license    : MIT
component  : programming.python
summary    : Path utilities for Python
description: |
    Path utilities for Python
builddeps  :
    - python-setuptools
build      : |
    %python_setup    
install    : |
    %python_install
